gh #30 Deprecate DTCP related APIs
rdkcentral/rdk-halif-device_settings pull request #31
Opened 2024-04-26 12:43 UTC by krishna-1809

2024-04-26 13:24 UTC, ddevad approved these changes

2024-04-29 09:15 UTC, hari22yuva requested changes
Can you please update L1 test cases also for the same

2024-04-29 10:24 UTC, krishna-1809 commented on include/dsVideoPort.h
> - * @brief Enables/Disables the DTCP of a video port.
Updated L1 Tests
https://github.com/rdkcentral/rdk-halif-test-device_settings/pull/41

2024-05-08 10:26 UTC, hari22yuva commented
@krishna-1809 Update the description

2024-05-08 15:17 UTC, hari22yuva approved these changes

2024-05-08 15:17 UTC, merged