Interface changes to support AIDL changes
rdkcentral/rdk-halif-device_settings pull request #33
Opened 2024-04-29 13:29 UTC by bhanucbp

2024-04-29 13:30 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/rdkcentral/rdk-halif-device_settings?pullRequest=33) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/rdkcentral/rdk-halif-device_settings?pullRequest=33) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/rdkcentral/rdk-halif-device_settings?pullRequest=33) it.</sub>

2024-07-26 13:40 UTC, Ulrond reviewed
what's holding this from being merged specifically?

2024-07-26 13:42 UTC, Ulrond commented on include/dsDisplay.h
> + * @warning  This API is Not thread safe
remove this everywhere, it's not required. You’ve stated it in your markdown overview.

Threading Model
This interface is not required to be thread safe

2024-07-26 13:42 UTC, Ulrond commented on include/dsDisplay.h
> + * @param[in] maxEDIDSize - length of the EDID buffer data. Min value is 0
invalid value surely would be zero?

2024-07-26 13:44 UTC, Ulrond commented on include/dsHdmiIn.h
> + * @warning  This API is Not thread safe.
remove as unrequired.

2024-07-26 13:45 UTC, Ulrond commented on include/dsHdmiIn.h
> + * For Sink devices this function gets the maximum size of EDID data corresponds to the given input port.
then the function should be stated as

`dsGetSinkEDIDBytesMaxSize` surely?

2024-07-26 13:45 UTC, Ulrond commented on include/dsHost.h
> + * @warning  This API is Not thread safe.
remove everwhere.

2024-07-26 13:46 UTC, Ulrond commented on include/dsHost.h
> + * @retval dsERR_OPERATION_NOT_SUPPORTED    - The attempted operation is not supported
under what condition would it be not supported? can't see this as a valid return code?

2024-07-26 13:48 UTC, Ulrond requested changes
some odd things defined in this.

2024-07-26 13:48 UTC, Ulrond commented on include/dsHost.h
> + * @warning  This API is Not thread safe.
remove warning everywhere.

2024-07-26 13:48 UTC, Ulrond commented on include/dsHost.h
> + * @param[in]  maxEDIDLength   - length of host EDID. Min value of 0.  Max value of 2048
can't be zero... You need to set a #define with a reasonable buffer size so that it's used here and the documention should state that.

2024-07-26 13:48 UTC, Ulrond commented on include/dsDisplay.h
> + * @retval dsERR_OPERATION_NOT_SUPPORTED    - The attempted operation is not supported
why would this occur? `dsERR_OPERATION_NOT_SUPPORTED` ? Was this added to all functions due to AIDL?

2025-02-12 09:40 UTC, srinivasgtl commented
This PR is not required as AIDL work elements will be considered with a new design.

2025-02-12 09:40 UTC, closed without merging