RDKE-41 Enhance component versioning and standard build support
rdkcentral/rdk-halif-device_settings pull request #34
Opened 2024-04-29 23:30 UTC by arun-madhavan-013

Enhance component versioning and standard build support by decoupling the install directory restructuring.

**Problem:**

- There is no build time confirmation on which version of Header is available.
- There is a hard dependency on the path of headers while building. If https://github.com/rdk-e/meta-rdk-halif-headers/commit/6945d98238fd271852ef0fe949280cf503813808 similar change happens it breaks the build if respective changes are not made in other layers(vendor & middleware).

**How it helps:**
Newly introduced pkg-config file will have the header component version and standard build flow can detect it.
when pkg-config is having 2.0.0
```
VM2[26/Apr|17:46:31]git# pkg-config --cflags 'halif-devicesettings >= 2.0.0' --print-errors
Requested 'halif-devicesettings >= 2.0.0' but version of DSHALHeaders is 1.0.8
VM2[26/Apr|17:46:58]git#
```
when pkg-config is having 1.0.8
```
VM2[26/Apr|17:46:59]git# pkg-config --cflags 'halif-devicesettings >= 1.0.8' --print-errors
-I/home/amadha013/community/build-raspberrypi4-64-rdk-mc/tmp/work/raspberrypi4-64-rdk-mc-vendor-rdkmllib32-linux-gnueabi/lib32-devicesettings-hal-raspberrypi4/1.0.0-r0/lib32-recipe-sysroot/usr/include/rdk/halif/ds-hal
VM2[26/Apr|17:47:06]git#
```
When vendor or middleware component builds; it can do a standard find pkg-config step and get the respective header installation path provided by **_halif-devicesettings.pc_** even if it is non-standard location. This helps to decouple the compile flag modification required to match Problem statement 2 similar changes.
**One-time change required in meta-rdk-halif-headers**

Install the respective pkg-config file from meta-rdk-halif-headers recipe.
```
diff --git a/recipes-rdk-halif-headers/devicesettings/devicesettings-hal-headers.bb b/recipes-rdk-halif-headers/devicesettings/devicesettings-hal-headers.bb
index 0826887..d433e60 100644
--- a/recipes-rdk-halif-headers/devicesettings/devicesettings-hal-headers.bb
+++ b/recipes-rdk-halif-headers/devicesettings/devicesettings-hal-headers.bb
@@ -18,7 +18,7 @@ LIC_FILES_CHKSUM = "file://LICENSE;md5=175792518e4ac015ab6696d16c4f607e"

 SRC_URI = "${CMF_GITHUB_ROOT}/rdk-halif-device_settings;${CMF_GITHUB_SRC_URI_SUFFIX}"

-inherit allarch
+inherit allarch pkgconfig

 S = "${WORKDIR}/git"

@@ -35,6 +35,9 @@ ALLOW_EMPTY_${PN} = "1"
 do_install() {
     install -d ${D}${includedir}/rdk/halif/ds-hal
     install -m 0644 ${S}/include/*.h ${D}${includedir}/rdk/halif/ds-hal
+
+    install -d ${D}${libdir}/pkgconfig
+    install -m 0644 ${S}/../halif-devicesettings.pc ${D}${libdir}/pkgconfig/
 }

 do_install[vardepsexclude] += "S"
```

2024-05-03 10:29 UTC, Ulrond requested changes
this cannot be a fork, contributing to this code is via branching the codebase only, and raising a ticket in the issue list, and using that as the branch name.

Generating a pull request to develop from the feature/ghxx_synopsis code change.

See -> https://github.com/rdkcentral/rdk-halif-device_settings/blob/main/CONTRIBUTING.md

2024-05-03 12:18 UTC, arun-madhavan-013 commented
Hi @Ulrond ,
I'm facing error when I do a direct push as below:
```
VM2[03/May|12:15:39]rdk-halif-device_settings$ git push
fatal: The current branch 35_build_support_enhancement has no upstream branch.
To push the current branch and set the remote as upstream, use

    git push --set-upstream origin 35_build_support_enhancement

VM2[03/May|12:15:42]rdk-halif-device_settings$ git push --set-upstream origin 35_build_support_enhancement
remote: Permission to rdkcentral/rdk-halif-device_settings.git denied to arun-madhavan-013.
fatal: unable to access 'https://github.com/rdkcentral/rdk-halif-device_settings.git/': The requested URL returned error: 403
VM2[03/May|12:15:48]rdk-halif-device_settings$
VM2[03/May|12:16:05]rdk-halif-device_settings$ git remote -v
origin  https://github.com/rdkcentral/rdk-halif-device_settings.git (fetch)
origin  https://github.com/rdkcentral/rdk-halif-device_settings.git (push)
VM2[03/May|12:16:11]rdk-halif-device_settings$
```
Without forking and adding a commit; i'm not able to create a PR.
Could you please advise on this ?

2024-05-16 09:45 UTC, Ulrond commented
ok you've been added to the project so you should be able to create a branch, but why is this change being added to this repo?

2024-05-16 09:46 UTC, Ulrond reviewed
please arrange a call to discuss this.

Headerfiles are not fixed location, and they do not specify an included dir.

it's upto the project manifest and the .bb file to set the project requirements not this header file.

2024-05-16 10:48 UTC, Ulrond requested changes
not something that should be committed to the header file.

2024-12-24 16:08 UTC, closed without merging