TDK-7908: Modify dsHost hal header
rdkcentral/rdk-halif-device_settings pull request #52
Opened 2024-06-20 14:10 UTC by saniya-09

Reason for change: Added @post tag in dsHost interface file
Risks: Low
Test Procedure: Check the code

2024-06-20 14:10 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/rdkcentral/rdk-halif-device_settings?pullRequest=52) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/rdkcentral/rdk-halif-device_settings?pullRequest=52) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/rdkcentral/rdk-halif-device_settings?pullRequest=52) it.</sub>

2024-06-21 09:50 UTC, srinivasgtl approved these changes
Approved. These are part of architecture review comments.

2024-06-21 09:57 UTC, hari22yuva requested changes
Need a github issue for this PR

2024-06-24 08:48 UTC, hari22yuva commented
duplicate PR 
Refer this issues 
https://github.com/rdkcentral/rdk-halif-device_settings/issues/50

2024-06-24 08:48 UTC, closed without merging